
title: StreamHub
description: Static-first community hub for streamers
url: ""   # set your custom domain or repo pages URL
baseurl: "" # if using project site like /repo-name, set to "/repo-name"

theme: minima

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

nav:
  - title: 일정
    url: /schedule/
  - title: 신규 크리에이터
    url: /creators/
  - title: 클립
    url: /clips/
  - title: 튜토리얼
    url: /tutorials/
  - title: 커뮤니티
    url: /community/
  - title: 장비
    url: /gear/
  - title: 어워즈
    url: /awards/
  - title: 트렌드
    url: /trends/
  - title: 참여하기
    url: /contribute/
  - title: 소개
    url: /about/

giscus:
  enable: false
  repo: ""
  repo_id: ""
  category: ""
  category_id: ""
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "light"
  lang: "ko"

ads:
  enable_right: true
  enable_footer: true

auto_sources:
  youtube_channels: []
  max_items_per_channel: 10

collections:
  tutorials:
    output: true
    permalink: /tutorials/:name/

defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: post

exclude:
  - node_modules
  - vendor
  - scripts
  - schemas
  - .github
  - README.md
  - LICENSE-MIT
  - LICENSE-CC-BY-4.0
  - CODE_OF_CONDUCT.md
  - Gemfile
  - Gemfile.lock
  - out
